# Generated by Django 4.2.18 on 2025-02-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvarient_sizevarient_product_size_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Size_variant',
            field=models.ManyToManyField(blank=True, to='products.sizevarient'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_variant',
            field=models.ManyToManyField(blank=True, to='products.colorvarient'),
        ),
    ]
