# Generated by Django 4.2.18 on 2025-02-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_size_variant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Size_variant',
            new_name='size_variant',
        ),
    ]
