# Generated by Django 4.2.18 on 2025-02-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_size_variant_product_size_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_variant',
        ),
        migrations.AddField(
            model_name='product',
            name='Size_variant',
            field=models.ManyToManyField(blank=True, to='products.sizevarient'),
        ),
    ]
