# Generated by Django 4.2.18 on 2025-02-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_size_variant_product_size_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Size_variant',
            new_name='size_variant',
        ),
    ]
